### PR TITLE
Deploy CronJobs

### PR DESCRIPTION
**Pull request by aluminiumgeek**
- Support deploying of CronJobs
- Use `imagePullSecret` when specified
- Release ckan v0.0.18

### CODE REVIEW

**Comment by akariv** [comment]
1. @aluminiumgeek please - releases should only be made using tagged commits.
2. Please update the documentation in ckan-cloud-operator (values file reference) with explanations of the new properties you've added.

**Review by akariv — CHANGES_REQUESTED** [review]
See above ^

**Comment by aluminiumgeek** [comment]
@akariv done (also added values reference to the CCO `azure-integration` branch)

**Comment by akariv** [comment]
@aluminiumgeek you need to let CI build the release and deploy it, not push it in the PR.

**Comment by akariv** [comment]
Now that it's removed please create a tagged commit (0.0.18-rc2)

**Pull request merged**
